### ISSUE TITLE
How to do transforms?

### ISSUE THREAD

**Issue by rwwagner90** [dfreeman/ember-cli-node-assets#10]
Can something like this be done with this library?

```
 app.import('vendor/redux-actions.js', {
      using: [{ transformation: 'amd', as: 'redux-actions' }]
    });
```

**Comment by foxnewsnetwork** [comment]
apparently, it's `processTree` and not `postprocessTree` as the README suggests... probably a documentation bug lol

**Comment by dfreeman** [comment]
@foxnewsnetwork Yikes! Sorry about the typo. The implementation and all the tests agreed on `processTree`, but the README didn't get the memo—it's updated now 🙂 

What you've got there looks good; I've been noodling lately on whether there's a way to cleanly create something to simplify importing CommonJS/ES2015 packages from npm via Webpack. I'm considering trying to pull out some of the work I did [here](https://github.com/bgentry/ember-apollo-client/pull/12/files#diff-168726dbe96b3ce427e7fedce31bb0bcR15) into an "ember-cli-webpack", but there are some subtleties around duplication and customization I want to think through first.

@rwwagner90 I forget the exact outcome of our conversation about this on Slack the other day—are we good to close this issue?

**Comment by rwwagner90** [comment]
@foxnewsnetwork you shouldn't need any `app.import` stuff, or the included hook at all, as this library does it all for you. I used the undocumented amd stuff in ember-redux-actions https://github.com/foxnewsnetwork/ember-redux-actions/blob/master/index.js#L12

As for getting things in the right format though, probably still need some of the hacky webpack stuff, unless @dfreeman builds something in as he mentioned 😄 .

@dfreeman we're good to close, just need that documentation updated 👍
