### ISSUE TITLE
Ember build fails no matter what

### ISSUE THREAD

**Issue by fr0gs** [dfreeman/ember-cli-node-assets#12]
Hello, I am trying to add the **mdbootstrap** package into my build process. This is my ember-cli-build.js, I cannot seem to see what does not follow with the specs:

```
  var app = new EmberApp(defaults, {
    nodeAssets: {
      'mdbootstrap': {
        vendor: {
          srcDir: 'mdbootstrap',
          destDir: 'mdbootstrap',
          include: ['css/bootstrap.min.css', 'mdb.min.css', 'js/bootstrap.min.js', 'js/mdb.min.js', 'js/tether.min.js']
        },
        public: {
          srcDir: 'mdbootstrap',
          destDir: 'assets',
          include: ['font/**/*', 'img/**/*']
        }
      }
    }
  });


  app.import('vendor/mdbootstrap/bootstrap.min.css')
...
```

I keep receiving this error:

```
Build failed.
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, scandir '/home/esteban/gits/oferteos-frontend-ember/tmp/funnel-input_base_path-n5Xq7kfJ.tmp/mdbootstrap/'
  at Object.fs.readdirSync (fs.js:913:18)
  at _walkSync (/home/esteban/gits/oferteos-frontend-ember/node_modules/walk-sync/index.js:64:18)
  at Function.entries (/home/esteban/gits/oferteos-frontend-ember/node_modules/walk-sync/index.js:40:10)
  at Funnel.processFilters (/home/esteban/gits/oferteos-frontend-ember/node_modules/broccoli-funnel/index.js:298:26)
  at Funnel.build (/home/esteban/gits/oferteos-frontend-ember/node_modules/broccoli-funnel/index.js:236:10)
  at /home/esteban/gits/oferteos-frontend-ember/node_modules/broccoli-plugin/read_compat.js:93:34
  at tryCatch (/home/esteban/gits/oferteos-frontend-ember/node_modules/rsvp/dist/rsvp.js:539:12)
  at invokeCallback (/home/esteban/gits/oferteos-frontend-ember/node_modules/rsvp/dist/rsvp.js:554:13)
  at publish (/home/esteban/gits/oferteos-frontend-ember/node_modules/rsvp/dist/rsvp.js:522:7)
  at flush (/home/esteban/gits/oferteos-frontend-ember/node_modules/rsvp/dist/rsvp.js:2414:5)
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)
..(etc)..
```

I have tried with variations of the directories, also installing old versions of Ember (I use 2.11) down to 2.8, but the error remains the same.

**Comment by dfreeman** [comment]
Hi @fr0gs! Two things jump out at me that look to be misconfigured:
 - `srcDir` is relative to the root of the package, so unless `mdbootstrap` puts all of its files inside a directory in the package that's also called `mdbootstrap` (which it doesn't look like it does), you can just leave `srcDir` out completely
 - the files you specify inside the `include` array keep their directory structure when they move into `destDir`, so you'd need to change this:
   ```js
   app.import('vendor/mdbootstrap/bootstrap.min.css');
   ```
   to this:
   ```js
   app.import('vendor/mdbootstrap/css/bootstrap.min.css');
   ```

If you want, you could also just `include: ['**.{js,css}']` in your `vendor` configuration so you don't have to repeat all the file names both there and in your `app.import()` calls 🙂

**Comment by fr0gs** [comment]
Worked perfectly!

I am sorry, but I found the line:

```
srcDir: The base directory relative to which includes are specified. Defaults to the root of the npm package.
```

misleading, as I understood that defaulting to the root of the npm packaged would involve me specifying the root manually in srcDir (relative to node_modules), and hence the hash key of nodeAssets was simply a naming scheme.

Thank you!

**Comment by dfreeman** [comment]
@fr0gs Thanks for the feedback on the doc! You're definitely right that that could be clearer. Would something like this read better?

```
srcDir: The base directory (based at the root of the package), relative to which includes are specified. Defaults to '', which represents the package root.
```

**Comment by fr0gs** [comment]
@dfreeman definitely :) 

thank you!
