### ISSUE TITLE
Warning: ignoring input sourcemap

### ISSUE THREAD

**Issue by kybishop** [dfreeman/ember-cli-node-assets#18]
After [importing popper.js for ember-popper](https://github.com/kybishop/ember-popper/blob/master/index.js#L13), a warning is printed when we run `ember s` for the addon's dummy app.

```
$: ember s
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
Warning: ignoring input sourcemap for vendor/popper.js/popper.js because ENOENT: no such file or directory, open '/Users/kybishop/github/ember/ember-popper/tmp/source_map_concat-input_base_path-3H3vcPOT.tmp/vendor/popper.js/popper.js.map'
```

More than happy to help diagnose whether or not this issue stems from ember-cli-node-assets, or a misconfigured build in the popper.js project itself, but I might need a bit of a primer on what the general issue _actually_ is ;)

**Comment by dfreeman** [comment]
I'd guess that error is being emitted by `broccoli-sourcemap-concat` when all the imported files are being concatenated together into your `vendor.js`. Probably `popper.js` has a sourcemap comment at the bottom of it, and the concat step is complaining because it can't find the sourcemap it references.

Total shot in the dark, but I'd try something like this:

```js
'popper.js': {
  srcDir: 'dist/umd',
  import: ['popper.js'],
  vendor: ['popper.js.map']
}
```

**Comment by kybishop** [comment]
Spot on about the sourcemap comment. Your fix was very close; turns out it needed to be thrown into the import array.

Going to close this out, but this exposes a separate issue:

I'm left in a small pickle where I either include a sourcemap in my final build, or live with the warning but enjoy a smaller final build size. It would be awesome if there were a way to optionally strip sourcemaps in prod via ember-cli-node-assets.

@dfreeman any thoughts on the above? We might be able to do this via a broccolli plugin if one doesn't already exist.

**Comment by dfreeman** [comment]
> I'm left in a small pickle where I either include a sourcemap in my final build, or live with the warning but enjoy a smaller final build size.

I would expect importing the sourcemap only impacts the size of your `vendor.js.map` — are you seeing it bloat your actual `vendor.js`?
