### ISSUE TITLE
Support for treeForStyles?

### ISSUE THREAD

**Issue by lukemelia** [dfreeman/ember-cli-node-assets#21]
I'd love to be able to use ember-cli-node-assets to pull SCSS into my app/styles tree. As far as I can tell, it would be fairly trivial to extend the project to support this. I understand if it is outside the scope though. What do you think?

**Comment by dfreeman** [comment]
It would be pretty straightforward to do, but I'd like to understand the use case a little better 🙂 

Unless I'm mistaken, `ember-cli-sass` already allows you `@import` files from the vendor tree, right? What's the advantage of bringing the SCSS files into the styles tree instead?

**Comment by lukemelia** [comment]
Ah, I was not aware of this. Let me experiment and I'll come back to close or elucidate.

**Comment by lukemelia** [comment]
Works brilliantly. For any future travelers:

```js
    // ember-cli-build.js
    // ...
    sassOptions: {
      includePaths: [
        'node_modules/package-you-want-to-import-scss-from'
      ]
    }
    // ...
   // then just @import a path relative to that package
```

Thanks @dfreeman!
