### ISSUE TITLE
Import js for fastboot 1.0

### ISSUE THREAD

**Issue by vlascik** [dfreeman/ember-cli-node-assets#22]
This addon could use a way to wrap imported js libraries for Fastboot 1.0 automatically, something along the lines of:
```javascript
  treeForVendor(vendorTree) {
    let icheckTree = new Funnel(path.dirname(require.resolve('icheck/icheck.js')), {
      files: ['icheck.js'],
    });
    icheckTree = map(icheckTree, (content) => `if (typeof FastBoot === 'undefined') { ${content} }`);

    return new MergeTrees([vendorTree, icheckTree]);
  },

  included: function(app) {
    this._super.included(app);

    app.import('vendor/icheck.js');
```

perhaps via separate `fastbootImport` config variable, similar to `import`?

**Comment by vlascik** [comment]
Seems that there is ember-cli PR to create a new app.import transformation similar to AMD coming.
Maybe there should be a shorthand to import with AMD/fastboot transformations, that would utilize these.

**Comment by dfreeman** [comment]
This addon really aims to be a pretty light layer over manual use of `broccoli-funnel` on the resolved root directory of a node package. The existing `import` key aims to be a very simple shorthand that intentionally doesn't support doing imports with complex config.

Ember CLI itself will have support for importing from `node_modules` soon, at which point the clock starts ticking for this addon to be completely obsoleted. Given that, I'm hesitant to add any new functionality.

**Comment by vlascik** [comment]
Well, soon can mean anything from 3 months to two years in ember time :) We've seen this before.
Anyway, ok, I'll close this, and maybe do a fork/PR later.

**Comment by dfreeman** [comment]
@vlascik By "soon" I actually mean "soon" — it's already on `master` in ember-cli https://github.com/ember-cli/ember-cli/pull/7045 🙂
