### ISSUE TITLE
Way to deal with FastBoot incompatible npm packages

### ISSUE THREAD

**Issue by kybishop** [dfreeman/ember-cli-node-assets#23]
Sometimes npm packages rely on things that aren't available in FastBoot (like `window` or `document`).

Might it make sense to add an option exclude them when in a FastBoot build? Maybe something like `excludeInFastBoot: true`.

Alternatively, this could be handled in the app itself, though it probably wouldn't be as pretty ;)

Happy to implement this, or perhaps add docs for the latter describing how to exclude an asset when in FastBoot.

**Comment by dfreeman** [comment]
Hi @kybishop — I actually just merged a PR from @rwwagner90 adding information on [how to deal with Fastboot to the README](https://github.com/dfreeman/ember-cli-node-assets#addons-with-fastboot). For the reasons outlined in https://github.com/dfreeman/ember-cli-node-assets/issues/22, I'm wary of adding any real additional functionality into this addon at this point, but I think the solution described there should work well 🙂

**Comment by rwwagner90** [comment]
@kybishop fancy meeting you here 😂 . I think this works with the `processTree` tweaks I documented. Happy to help if there are issues.

**Comment by kybishop** [comment]
hah, nice. Closing this out. Thanks for getting to it first @rwwagner90!
