### ISSUE TITLE
Possible path issue on windows

### ISSUE THREAD

**Issue by knownasilya** [dfreeman/ember-cli-node-assets#4]
Seeing the following:

```
The Broccoli Plugin: [Funnel: Funnel
 vendor/bootstrap\dist\css
 bootstrap\dist\css
include:1] failed with:
Error: ENOENT: no such file or directory, mkdir 'C:\git\MLDP\src\MLDP.WebApp\tmp\funnel-output_path-tlEkWW1P.tmp\bootstrap\dist\css'
```

Notice the one "unix slash" in the path above.

with this config: 

```js
    nodeAssets: {
      bootstrap: {
        import: ['dist/css/bootstrap.css', 'dist/css/bootstrap.css.map']
      },    
      'ember-light-table': {
        import: ['addon/styles/addon.css']
      }     
    }
```

Using 0.1.4

**Comment by knownasilya** [comment]
Debug output

```
C:\git\MLDP\src\MLDP.WebApp> ember build --watch --output-path='../MLDP.Web/wwwroot'
- Building  ember-cli-node-assets importing vendor\bootstrap\dist\css\bootstrap.css with options {} +0ms
 ember-cli-node-assets importing vendor\bootstrap\dist\css\bootstrap.css.map with options {} +56ms
 ember-cli-node-assets importing vendor\ember-light-table\addon\styles\addon.css with options {} +1ms
 ember-cli-node-assets adding tree for bootstrap at C:\git\MLDP\src\MLDP.WebApp\node_modules\bootstrap { destDir: 'bootstrap', include: [ 'dist/css/bootstrap.css', 'dist/css/bootstrap.css.map' ] } +12s
 ember-cli-node-assets adding tree for ember-light-table at C:\git\MLDP\src\MLDP.WebApp\node_modules\ember-light-table { destDir: 'ember-light-table', include: [ 'addon/styles/addon.css' ] } +5ms
- BuildingThe Broccoli Plugin: [Funnel: Funnel
 vendor/bootstrap\dist\css
 bootstrap\dist\css
include:1] failed with:
Error: ENOENT: no such file or directory, mkdir 'C:\git\MLDP\src\MLDP.WebApp\tmp\funnel-output_path-EAHKAKWd.tmp\bootstrap\dist\css'
```

**Comment by knownasilya** [comment]
Something about broccoli-funnel maybe? Any thoughts @stefanpenner

**Comment by dfreeman** [comment]
@knownasilya the debug output all looks like what I'd expect — waiting on an npm install inside a Windows VM at the moment, so in roughly 3-4 years I should be able to dig in ;)

**Comment by knownasilya** [comment]
FYI I just tried the alternative module by @kellyseldan, which uses funnel directly and that worked for me. Maybe something about the version of funnel you're using?

**Comment by dfreeman** [comment]
The funnel dependency here is `^1.0.1`, and it doesn't look like there's been a major release, so it should just be using the latest.

Interestingly, setting a `srcDir` for Bootstrap seems to work around whatever the issue is. This config works for me:

```js
    nodeAssets: {
      bootstrap: {
        srcDir: 'dist/css',
        import: ['bootstrap.css', 'bootstrap.css.map']
      },    
      'ember-light-table': {
        import: ['addon/styles/addon.css']
      }     
    }
```

This smells like something going on with broccoli-funnel to me, but I'm not quite sure what.

**Comment by dfreeman** [comment]
It looks like broccoli-funnel is failing to create the ancestor directories for the included files, and specifying `srcDir: 'dist/css'` bypasses that by putting the included files in the root of the output.

Another thing I missed before: the error isn't being thrown in the funnel created by this addon, but by the one instantiated [here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1477) in ember-cli.

@stefanpenner not sure what the root problem could be here, but it does seem to be Windows-specific. I can try and find some time this weekend to come up with a smaller reproduction, but if you have any intuitions about what could be going on here in the meantime, that would be fantastic.

The funnel instantiation basically amounts to this:
```js
new Funnel(new UnwatchedTree('C:\\Users\\IEUser\\Desktop\\test-app\\node_modules\\bootstrap'), {
  destDir: 'bootstrap',
  include: [ 'dist/css/bootstrap.css', 'dist/css/bootstrap.css.map' ]
})
```

**Comment by dfreeman** [comment]
Mentioned this in Slack, but just to capture the facepalm here as well, the issue was ultimately with the funnel produced by the `import` call because the mix of Windows and POSIX slashes in the path was causing problems.
