### ISSUE TITLE
Support import sourcemap file?

### ISSUE THREAD

**Issue by nightire** [dfreeman/ember-cli-node-assets#5]
Document says this is possible, but seems it will be omitted and never get any chance to import:

https://github.com/dfreeman/ember-cli-node-assets/blob/bb540165ebbbd3d280437148e09a94907ad41a10/index.js#L24

So does it still be supported or a future-possible feature?

**Comment by dfreeman** [comment]
Looks like this got lost in a bad merge [here](https://github.com/dfreeman/ember-cli-node-assets/commit/67db16f83bb2cecc0c04e7ea4971a65bfc1c40aa#diff-168726dbe96b3ce427e7fedce31bb0bcL147). Sorry about that!

I just pushed [a commit](https://github.com/dfreeman/ember-cli-node-assets/commit/1aa45a56c6458742569a1e0970b3e4b7bc2e26ae) that should take care of the issue, and I'll publish a new release shortly. I also filed [an issue](https://github.com/dfreeman/ember-cli-node-assets/issues/6) as a reminder to myself to get better unit testing in place so this kind of thing doesn't regress in the future!

**Comment by nightire** [comment]
Awesome, thank you veru much!

**Comment by XaserAcheron** [comment]
This likely isn't the greatest place to ask, but it's relevant, so:

How do you exactly use this feature? It's not in the docs and I'm having trouble figuring it out myself.

**Comment by dfreeman** [comment]
@XaserAcheron with the 0.2.x series of releases, you no longer need to do anything special for sourcemaps. As long as your [funnel](https://github.com/broccolijs/broccoli-funnel) configuration for a given package doesn't exclude the sourcemap file, Ember CLI should pick it up when it concatenates together the files you've `import`ed.

**Comment by XaserAcheron** [comment]
I'm getting `ENOENT: no such file or directory` warnings for sourcemaps for a couple of (non-Ember) imports. I'll try and post more details when I'm back at it tomorrow-ish.

**Comment by dfreeman** [comment]
> [EDIT] Well, I suppose a closed issue thread really isn't the best place for this at all. Welp.

Haha, I've seen worse abuse of old issue threads. Feel free to ping me on the Ember Slack tomorrow (I'm @dfreeman there too) with more details if you want, and I can try to help you debug what's going on 🙂
