### ISSUE TITLE
Dynamic Config Example Broken in 0.2.0-beta.1

### ISSUE THREAD

**Issue by Panman8201** [dfreeman/ember-cli-node-assets#8]
It seems the changes with 0.2.0-beta.1 changed the context in which the "custom function" is run. Following the [dynamic configuration example](https://github.com/dfreeman/ember-cli-node-assets#dynamic-configuration), now I get an error during build about `Cannot read property 'addonOptions' of undefined`.

If you need an example, I just moved [ember-froala-editor](https://github.com/froala/ember-froala-editor/blob/master/index.js) from importing files from bower deps to this addon. Works with 0.1.6 but not 0.2.0-beta.1

**Comment by dfreeman** [comment]
What jerk refactored everything and didn't include a test case for that? 😉 

Should be a quick fix — I'll take a look.

**Comment by dfreeman** [comment]
Just cut `0.2.0-beta.2` — should be fixed there.

**Comment by Panman8201** [comment]
Confirmed, works with beta 2. Thanks
